package com.admiral.diplom.accountmessagingdata;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(28327679778221ad4c97d1f9436bfbd6)
 */
@org.kie.api.definition.type.Label(value = "Activity")
public class Activity extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Account ID")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String account_id;
    
    @org.kie.api.definition.type.Label(value = "ID")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String id;
    
    @org.kie.api.definition.type.Label(value = "Last day")
    @org.kie.api.definition.type.Position(value = 1)
    private java.util.Date last_day;

    public Activity() {
    }

    public Activity(java.lang.String id, java.util.Date last_day, java.lang.String account_id) {
        this.id = id;
        this.last_day = last_day;
        this.account_id = account_id;
    }


    
    public java.lang.String getAccount_id() {
        return this.account_id;
    }

    public void setAccount_id(java.lang.String account_id) {
        this.account_id = account_id;
    }
    
    public java.lang.String getId() {
        return this.id;
    }

    public void setId(java.lang.String id) {
        this.id = id;
    }
    
    public java.util.Date getLast_day() {
        return this.last_day;
    }

    public void setLast_day(java.util.Date last_day) {
        this.last_day = last_day;
    }
}