package com.admiral.diplom.accountmessaging;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(8e74b50287705580a14baca53177e5a6)
 */
@org.kie.api.definition.type.Label(value = "Customer")
public class Account  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Date created")
    @org.kie.api.definition.type.Position(value = 1)
    private java.util.Date date_entered;
    
    @org.kie.api.definition.type.Label(value = "ID")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String id;
    
    @org.kie.api.definition.type.Label(value = "Last trade operation date")
    @org.kie.api.definition.type.Position(value = 2)
    private java.util.Date last_trade_operation_date;

    public Account() {
    }

    public Account(java.lang.String id, java.util.Date date_entered, java.util.Date last_trade_operation_date) {
        this.id = id;
        this.date_entered = date_entered;
        this.last_trade_operation_date = last_trade_operation_date;
    }


    
    public java.util.Date getDate_entered() {
        return this.date_entered;
    }

    public void setDate_entered(java.util.Date date_entered) {
        this.date_entered = date_entered;
    }
    
    public java.lang.String getId() {
        return this.id;
    }

    public void setId(java.lang.String id) {
        this.id = id;
    }
    
    public java.util.Date getLast_trade_operation_date() {
        return this.last_trade_operation_date;
    }

    public void setLast_trade_operation_date(java.util.Date last_trade_operation_date) {
        this.last_trade_operation_date = last_trade_operation_date;
    }
}