package com.admiral.diplom.accountmessaging;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(51bb1ce4453c9ba685f32892b881b8ca)
 */
@org.kie.api.definition.type.Label(value = "Activity")
public class Activity  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "ID")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String id;
    
    @org.kie.api.definition.type.Label(value = "Last day")
    @org.kie.api.definition.type.Position(value = 1)
    private java.util.Date last_day;

    public Activity() {
    }

    public Activity(java.lang.String id, java.util.Date last_day) {
        this.id = id;
        this.last_day = last_day;
    }


    
    public java.lang.String getId() {
        return this.id;
    }

    public void setId(java.lang.String id) {
        this.id = id;
    }
    
    public java.util.Date getLast_day() {
        return this.last_day;
    }

    public void setLast_day(java.util.Date last_day) {
        this.last_day = last_day;
    }
}